### ISSUE TITLE
Fix stupid security alert from tar ??

### ISSUE THREAD

**Issue by cvillhauer** [cvillhauer/Pathfinder-Animal-Handling2#11]
https://github.com/cvillhauer/Pathfinder-Animal-Handling2/network/alerts

**Comment by rdrrichards** [comment]
This probably won't be addressed until ng 8 comes out

**Comment by cvillhauer** [comment]
@rdrrichards fixed? I think?

**Comment by rdrrichards** [comment]
Yes

**Comment by cvillhauer** [comment]
Yay! Another one bites the dust 👍
