### ISSUE TITLE
Need a favicon

### ISSUE THREAD

**Issue by cvillhauer** [cvillhauer/Pathfinder-Animal-Handling2#15]
I'm looking at you @rdrrichards 🥇

**Comment by rdrrichards** [comment]
Stop looking at me!!! :)

I will start looking for something that makes sense. I should be able to come up with some ideas.

**Comment by cvillhauer** [comment]
Don't you know that you're always allowed to say no??

**Comment by rdrrichards** [comment]
That's my line!
