### ISSUE TITLE
Favicon isn't transparent

### ISSUE THREAD

**Issue by cvillhauer** [cvillhauer/Pathfinder-Animal-Handling2#28]

**Comment by rdrrichards** [comment]
I'm not sure this is a terrible thing. When I view the site with a browser like Edge, and I use the dark theme, I would guess the icon would look like nothing was there if it had a transparent background. Maybe a grey background would be better? Just guessing, really. We can play with it.

**Comment by cvillhauer** [comment]
Does the icon have to be black/grey? What about... PINK!? Or green? :-) I think that would look nice on a transparent background regardless of browser theme?

**Comment by rdrrichards** [comment]
Pink, huh? Ah... _sure_! I will see about making that happen. :)

Actually, I think I will play with a few color schemes. You can choose the one you like.

**Comment by cvillhauer** [comment]
I'm eager to see what you come up with!

And please note, I am by no means committed to the weird pea green color that is currently the background!! It was just something to start with that wasn't grey.

**Comment by rdrrichards** [comment]
Can we close this one?

**Comment by cvillhauer** [comment]
I like to wait until the fix is merged to master before I close these... but, I think I'm about ready for that. I can't go further on celestial/fiendish without the Attack functionalities implemented. I'll do a PR if you want to do a code review?

**Comment by rdrrichards** [comment]
I can wait. Just trying to stay on top of things. 👍
