### ISSUE TITLE
Items brought in from Creature Service are objects, not Creatures?

### ISSUE THREAD

**Issue by cvillhauer** [cvillhauer/Pathfinder-Animal-Handling2#29]
I can't use functions in the model.creature class on this.selectedCreature within the spell.component onSummon() function. I get this error:

this.selectedCreature.augmentSummoning is not a function

**Comment by rdrrichards** [comment]
You may have to make `augmentSummoning` in the creature class static in order for it to work how you like. 

    static augmentSummoning(...) {...}

**Comment by cvillhauer** [comment]
I couldn't get it to work by adding "static" ... I'm actually adding a few new functions to support alignment functionality and I need to call them before a creature is actually summoned. But it's erroring and telling me selectedCreature doesn't have that function. I am able to reproduce it by calling augmentSummon too, so I don't think it's a problem with my new code. I could check it in if you want to take a closer look?

**Comment by rdrrichards** [comment]
If you would like me to take a look, then publish your branch and do a push. But, if you want to see about finding and fixing the issue on your own, I can dig that too. It's probably something silly. It always is! :)
