### ISSUE TITLE
Update to Angular 8?

### ISSUE THREAD

**Issue by cvillhauer** [cvillhauer/Pathfinder-Animal-Handling2#31]

**Comment by rdrrichards** [comment]
We can. Do you want me to give it a go? I have done that will all my personal projects, worked out ok.

**Comment by cvillhauer** [comment]
I'm so glad you asked :-) Yes, have at it, please!

To be honest, I'd probably never get around to updating angular versions if I was working on this by myself.

**Comment by rdrrichards** [comment]
PR with the changes ready for review

**Comment by cvillhauer** [comment]
Awesome! Thank you 🥇 🥇 🥇 🥇 

I'll take a look when I get home tonight

**Comment by cvillhauer** [comment]
Looks good!! Thank you @rdrrichards
