### ISSUE TITLE
AugmentSummoning is stacking multiple times if you summon multiple creatures

### ISSUE THREAD

**Issue by cvillhauer** [cvillhauer/Pathfinder-Animal-Handling2#56]
To reproduce, cast Summon Nature's Ally II for a level 2 Wolf.
Note that the Wolf has a Bite attack with Trip attackEffect +4.
Then, case Summon Nature's Ally III for level 2 Wolf, and you'll get multiple wolves.
The Wolves have Bite attacks with Trip +6-8 depending on how many Wolves you got.

I think the cause is that AugmentSummoning from onSummon() are affecting selectedCreature as well as newCreature?

**Comment by rdrrichards** [comment]
I took a look at this, but I am not sure based on the description above what the issue is. How should this behave?
